const router=require('express').Router();
const s=require('./estadia.servicio');
const condiciones=require('./condiciones.servicio');
const handler=fn=>async(req,res)=>{try{res.json(await fn(req));}catch(e){if(e.code==='P2002')return res.status(409).json({error:'Esta persona ya tiene un ingreso activo en otra estadía.'});if(!e.statusCode)console.error('[estadia]',e);res.status(e.statusCode||500).json({error:e.statusCode?e.message:'No se pudo completar la operación de estadía.'});}};
router.get('/alojados',handler(r=>s.alojados(String(r.query.q||'').slice(0,100))));
router.get('/:reservaId/ocupantes',handler(r=>s.listar(r.params.reservaId)));
router.get('/:reservaId/condiciones',handler(r=>condiciones.obtener(r.params.reservaId)));
router.put('/:reservaId/condiciones/:habitacionId',handler(r=>condiciones.guardar(r.params.reservaId,r.params.habitacionId,r.body)));
router.get('/:reservaId/adicional-ocupacion',handler(r=>condiciones.preview(r.params.reservaId)));
router.post('/:reservaId/adicional-ocupacion',handler(r=>condiciones.aplicar(r.params.reservaId,r.body)));
router.post('/:reservaId/ocupantes',handler(r=>s.guardar(r.params.reservaId,null,r.body)));
router.put('/:reservaId/ocupantes/:id',handler(r=>s.guardar(r.params.reservaId,r.params.id,r.body)));
router.post('/:reservaId/ocupantes/:id/accion',handler(r=>s.accion(r.params.reservaId,r.params.id,r.body)));
router.get('/:reservaId/historial',handler(r=>s.historial(r.params.reservaId)));
router.post('/:reservaId/garantia',handler(r=>s.liquidarGarantia(r.params.reservaId,r.body)));
module.exports=router;
