import {test,expect,vi} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {MemoryRouter,Routes,Route} from 'react-router-dom';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {CheckOutReservaPage} from './CheckOutReservaPage';
import {obtenerCuenta} from './checkOut.api';
vi.mock('../../lib/sesion',()=>({useSesion:()=>({puede:()=>true,usuario:'Recepción'})}));
vi.mock('./checkOut.api',()=>({obtenerCuenta:vi.fn(),registrarVerificacion:vi.fn(),confirmarCheckOut:vi.fn()}));
vi.mock('../pagos-estadia/pagoEstadia.api',()=>({listarPagosEstadia:async()=>({pagos:[{id:1,garantiaSeparada:true,fecha:'2026-09-30',medios:[{id:1,medioPago:'Garantía recibida',importe:30000}],estado:'Pagado'},{id:2,fecha:'2026-09-30',medios:[{id:2,medioPago:'Seña efectiva',importe:40000}],estado:'Parcial'}]}),anularPagoEstadia:vi.fn()}));
vi.mock('../estadia/EstadiaPanel',()=>({Garantias:({editable})=><button disabled={!editable}>Liquidar garantía de prueba</button>}));
test('exige confirmar cargos, separa garantía de pagos y vuelve a confirmar si cambia la cuenta',async()=>{
  let cuenta={estadoReserva:'En curso',codigoConfirmacion:'TEST',huesped:{nombre:'Prueba'},fechaDesde:'2026-09-30',fechaHasta:'2026-10-02',habitaciones:[{habitacionId:1,numero:'301',verificada:true,subtotal:100000}],consumos:[],verificaciones:[],subtotales:{alojamiento:100000,serviciosAdicionales:0,verificacion:0},totalAdeudado:100000,totalPagado:40000,saldo:60000,garantiaPendiente:30000,garantias:[]};
  obtenerCuenta.mockImplementation(async()=>({...cuenta}));
  const qc=new QueryClient({defaultOptions:{queries:{retry:false}}});
  render(<QueryClientProvider client={qc}><MemoryRouter initialEntries={['/check-out/1']}><Routes><Route path="/check-out/:reservaId" element={<CheckOutReservaPage/>}/></Routes></MemoryRouter></QueryClientProvider>);
  const liquidar=await screen.findByRole('button',{name:'Liquidar garantía de prueba'});
  expect(liquidar).toBeDisabled();
  expect(screen.queryByText(/Garantía recibida/)).not.toBeInTheDocument();
  await screen.findByText(/Seña efectiva/);
  fireEvent.click(screen.getByRole('checkbox'));
  expect(liquidar).toBeEnabled();
  expect(screen.getByRole('button',{name:'Registrar pago'})).toBeDisabled();
  cuenta={...cuenta,garantiaPendiente:0,saldo:52000,totalPagado:48000};
  await qc.invalidateQueries({queryKey:['check-out','cuenta']});
  await waitFor(()=>expect(screen.getByRole('button',{name:'Registrar pago'})).toBeEnabled());
  cuenta={...cuenta,totalAdeudado:101000,saldo:53000};
  await qc.invalidateQueries({queryKey:['check-out','cuenta']});
  await waitFor(()=>expect(screen.getByRole('checkbox')).not.toBeChecked());
  expect(liquidar).toBeDisabled();
});
