import {useState} from 'react';
import {useQuery,useMutation,useQueryClient} from '@tanstack/react-query';
import {api} from '../../lib/api';
import {useSesion} from '../../lib/sesion';
import {Input} from '../../componentes/Input';
import {Button} from '../../componentes/Button';
const moneda=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(v||0);
export function CondicionesHabitaciones({reserva,editable}){
  const {usuario}=useSesion();const qc=useQueryClient();const [edicion,setEdicion]=useState({});const [error,setError]=useState('');const [preview,setPreview]=useState(null);
  const q=useQuery({queryKey:['condiciones',reserva.id],queryFn:()=>api.get(`/estadia/${reserva.id}/condiciones`).then(r=>r.data)});
  const m=useMutation({mutationFn:({accion,h})=>accion==='guardar'?api.put(`/estadia/${reserva.id}/condiciones/${h.habitacionId}`,{ocupacionIncluida:h.ocupacionIncluida??h.habitacion.capacidad,precioPersonaExtra:h.precioPersonaExtra,serviciosIncluidos:h.serviciosIncluidos,...edicion[h.id],operador:usuario}):accion==='calcular'?api.get(`/estadia/${reserva.id}/adicional-ocupacion`):api.post(`/estadia/${reserva.id}/adicional-ocupacion`,{items:preview.items,operador:usuario}),onSuccess:(r,v)=>{setError('');if(v.accion==='calcular')setPreview(r.data);else{setPreview(null);for(const k of ['condiciones','check-out','consumos-servicios','pagos-estadia','estadia-historial'])qc.invalidateQueries({queryKey:[k]});}},onError:e=>setError(e.response?.data?.error||'No se pudo actualizar las condiciones.')});
  return <div className="space-y-4"><h3 className="font-semibold">Condiciones de las habitaciones</h3><p className="text-sm text-piedra">El adicional por persona se carga a la habitación. Revisá primero la lista de ocupantes y sus fechas. Los cambios no alteran cargos ya registrados.</p>{q.isError&&<p role="alert">No se pudieron cargar las condiciones.</p>}{q.data?.map(h=><div key={h.id} className="border border-borde rounded p-3 space-y-2"><strong>Habitación {h.habitacion.numero} · {moneda(h.tarifaPactada??h.habitacion.tarifaPorNoche)} por noche</strong>{h.tarifaPactada==null&&<p className="text-xs text-piedra">Reserva anterior: no se conserva una tarifa pactada; se utiliza la tarifa disponible.</p>}<div className="grid sm:grid-cols-3 gap-3">{[['ocupacionIncluida','Personas incluidas',h.ocupacionIncluida??h.habitacion.capacidad],['precioPersonaExtra','Adicional por persona / noche',h.precioPersonaExtra],['serviciosIncluidos','Servicios incluidos',h.serviciosIncluidos||'']].map(([k,label,v])=><Input key={k} label={label} type={k==='serviciosIncluidos'?'text':'number'} min={k==='ocupacionIncluida'?1:0} step={k==='ocupacionIncluida'?1:0.01} disabled={!editable} value={edicion[h.id]?.[k]??v} onChange={e=>setEdicion({...edicion,[h.id]:{...edicion[h.id],[k]:e.target.value}})}/>)}</div>{editable&&<Button variante="secundario" cargando={m.isPending} onClick={()=>m.mutate({accion:'guardar',h})}>Guardar condiciones</Button>}</div>)}{editable&&reserva.estado==='En curso'&&<Button variante="secundario" cargando={m.isPending} onClick={()=>m.mutate({accion:'calcular'})}>Calcular adicionales por ocupación</Button>}{preview&&<div className="border border-borde rounded p-3"><h4 className="font-semibold">Propuesta de cargos</h4>{preview.items.map(i=><p key={i.claveOperacion}>Habitación {i.numero} · {i.fecha} · {i.cantidad} adicional(es): {moneda(i.monto)}</p>)}<p>Total: {moneda(preview.total)}</p>{preview.items.length>0&&<Button cargando={m.isPending} onClick={()=>m.mutate({accion:'aplicar'})}>Confirmar estos cargos</Button>}</div>}{error&&<p role="alert" className="text-error-texto">{error}</p>}</div>;
}
