import {render,screen,within,waitFor} from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {vi,it,expect,beforeEach} from 'vitest';
import {EstadiaPanel} from './EstadiaPanel';
import {api} from '../../lib/api';
vi.mock('../../lib/api',()=>({api:{get:vi.fn(),post:vi.fn(),put:vi.fn()}}));
vi.mock('../../lib/sesion',()=>({useSesion:()=>({usuario:'Operador prueba',puede:()=>true})}));
const reserva={id:50,estado:'En curso',fechaDesde:'2026-09-28',fechaHasta:'2026-09-30',habitaciones:[{id:10,numero:'101',capacidad:2},{id:11,numero:'102',capacidad:1}]};
function setup(){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}><EstadiaPanel reserva={reserva}/></QueryClientProvider>);}
beforeEach(()=>{vi.clearAllMocks();api.get.mockImplementation(url=>Promise.resolve({data:url.includes('/cuenta')?{habitaciones:[],garantias:[],totalAdeudado:0,totalPagado:0,saldo:0}:url==='/consumos-servicios'?[{id:1,habitacionId:10,descripcion:'Lavandería',tipoServicio:'Lavandería',cantidad:2,precioUnitario:50,monto:100,registradoPor:'Recepción',fechaHora:new Date().toISOString()}]:[]}));api.post.mockResolvedValue({data:{ok:true}});});
it('agrupa cargos por habitación sin solicitar el nombre del huésped',async()=>{setup();await userEvent.click(screen.getByRole('button',{name:'Cargos por habitación'}));expect(await screen.findByText(/Lavandería · 2/)).toBeInTheDocument();expect(screen.getAllByRole('button',{name:'Agregar cargo'})).toHaveLength(2);expect(screen.queryByLabelText(/huésped/i)).not.toBeInTheDocument();});
it('exige motivo y manda operador para anular un cargo',async()=>{setup();await userEvent.click(screen.getByRole('button',{name:'Cargos por habitación'}));await userEvent.click(await screen.findByRole('button',{name:'Anular'}));const confirmar=screen.getByRole('button',{name:'Confirmar anulación'});expect(confirmar).toBeDisabled();await userEvent.type(screen.getByLabelText('Motivo *'),'Carga duplicada');await userEvent.click(confirmar);await waitFor(()=>expect(api.post).toHaveBeenCalledWith('/consumos-servicios/1/anular',{motivo:'Carga duplicada',operador:'Operador prueba'}));});
it('permite cargar ocupantes de distintas habitaciones y no copia al titular automáticamente',async()=>{setup();await userEvent.click(screen.getByRole('button',{name:'Agregar persona'}));const dialog=screen.getByRole('dialog');await userEvent.type(within(dialog).getByLabelText('Nombre *'),'Ana');await userEvent.type(within(dialog).getByLabelText('Apellido *'),'Prueba');await userEvent.selectOptions(within(dialog).getByLabelText('Habitación *'),'11');await userEvent.click(within(dialog).getByRole('button',{name:'Guardar persona'}));await waitFor(()=>expect(api.post).toHaveBeenCalledWith('/estadia/50/ocupantes',expect.objectContaining({nombre:'Ana',apellido:'Prueba',habitacionId:'11',operador:'Operador prueba'})));});
