import { CondicionesHabitaciones } from "./CondicionesHabitaciones";
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { useSesion } from '../../lib/sesion';
import { Button } from '../../componentes/Button';
import { Input } from '../../componentes/Input';
import { Select } from '../../componentes/Select';
import { Modal } from '../../componentes/Modal';
import { ConsumoModal } from '../servicios-adicionales/ConsumoModal';
import { obtenerCuenta } from '../check-out/checkOut.api';

const moneda=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(v||0);
const detalleEvento=e=>{try{const d=JSON.parse(e.detalle);return [d.habitacionId?`Habitación ID ${d.habitacionId}`:null,d.motivo,d.monto!=null?moneda(d.monto):null,d.devolver!=null?`Devolución ${moneda(d.devolver)}`:null,d.aplicar!=null?`Aplicación ${moneda(d.aplicar)}`:null].filter(Boolean).join(" · ");}catch{return "";}};
const fecha=v=>v?new Date(v).toLocaleString('es-AR'):'—';
const activa=p=>p.asignaciones?.find(a=>!a.hasta);
const campos=[['nombre','Nombre','text',true],['apellido','Apellido','text',true],['tipoDocumento','Tipo de documento','text'],['numeroDocumento','Número de documento','text'],['paisDocumento','País emisor','text'],['motivoSinDocumento','Justificación sin documento','text'],['fechaNacimiento','Nacimiento','date'],['nacionalidad','Nacionalidad','text'],['paisResidencia','País de residencia','text'],['localidad','Localidad','text'],['domicilio','Domicilio','text'],['telefono','Teléfono','tel'],['email','Correo electrónico','email'],['fechaDesde','Ingreso previsto','date',true],['fechaHasta','Salida prevista','date',true]];
export function PersonaFormulario({persona={},reserva,personas=[],onGuardar,onClose,pendiente=false,error=''}){
  const [form,setForm]=useState(()=>({...persona,habitacionId:activa(persona)?.habitacionId||persona.habitacionId||reserva.habitaciones[0]?.id||'',fechaNacimiento:persona.fechaNacimiento?.slice(0,10)||'',fechaDesde:(persona.fechaDesde||reserva.fechaDesde||'').slice(0,10),fechaHasta:(persona.fechaHasta||reserva.fechaHasta||'').slice(0,10)}));
  return <form onSubmit={e=>{e.preventDefault();onGuardar(form);}} className="space-y-4 p-5">
    <p className="text-sm text-piedra">Los datos identifican al ocupante. Todos los cargos se asignan a la habitación.</p>
    <div className="grid gap-3 sm:grid-cols-2">{campos.map(([k,label,type,required])=><Input key={k} label={label+(required?' *':'')} type={type} required={required} maxLength={191} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/>)}
      <Select label="Habitación *" required value={form.habitacionId} onChange={e=>setForm({...form,habitacionId:e.target.value})}>{reserva.habitaciones.map(h=><option key={h.id} value={h.id}>Habitación {h.numero} · capacidad {h.capacidad}</option>)}</Select>
      <Select label="Adulto responsable (menores)" value={form.responsableId||''} onChange={e=>setForm({...form,responsableId:e.target.value})}><option value="">Sin asignar</option>{personas.filter(p=>p.id!==persona.id&&!['Cancelado','Retirado'].includes(p.estado)).map(p=><option key={p.id} value={p.id}>{p.nombre} {p.apellido}</option>)}</Select>
      {persona.id&&<Input label="Motivo del cambio de habitación" value={form.motivo||''} onChange={e=>setForm({...form,motivo:e.target.value})}/>}
    </div>
    {error&&<p role="alert" className="text-error-texto">{error}</p>}
    <div className="flex justify-end gap-2"><Button type="button" variante="secundario" onClick={onClose}>Cancelar</Button><Button type="submit" cargando={pendiente}>Guardar persona</Button></div>
  </form>;
}

export function EstadiaPanel({reserva,soloPersonas=false}){
  const {usuario,puede}=useSesion();const qc=useQueryClient();const [tab,setTab]=useState('Personas');const [editor,setEditor]=useState(null);const [cargoHabitacion,setCargoHabitacion]=useState(null);const [anular,setAnular]=useState(null);const [motivo,setMotivo]=useState('');const [error,setError]=useState('');
  const puedeEditar=(puede('gestionarReservas')||puede('gestionarCheckIn'))&&['Confirmada','En curso'].includes(reserva.estado);
  const puedeCargos=puede('registrarConsumoServicio')&&reserva.estado==='En curso';
  const puedeCuenta=puede('verPagosEstadia');
  const personas=useQuery({queryKey:['ocupantes',reserva.id],queryFn:()=>api.get(`/estadia/${reserva.id}/ocupantes`).then(r=>r.data)});
  const cuenta=useQuery({queryKey:['check-out','cuenta',String(reserva.id)],queryFn:()=>obtenerCuenta(reserva.id),enabled:!soloPersonas&&puedeCuenta});
  const cargos=useQuery({queryKey:['consumos-servicios','detalle',reserva.id],queryFn:()=>api.get('/consumos-servicios',{params:{reservaId:reserva.id}}).then(r=>r.data),enabled:!soloPersonas&&puede('verConsumosServicio')});
  const historial=useQuery({queryKey:['estadia-historial',reserva.id],queryFn:()=>api.get(`/estadia/${reserva.id}/historial`).then(r=>r.data),enabled:tab==='Historial'});
  const refrescar=()=>{for(const k of ['ocupantes','estadia-historial','check-out','consumos-servicios','pagos-estadia','reservas','alojados'])qc.invalidateQueries({queryKey:[k]});};
  const mutation=useMutation({mutationFn:async({tipo,data})=>{setError('');if(tipo==='guardar')return editor.id?api.put(`/estadia/${reserva.id}/ocupantes/${editor.id}`,{...data,operador:usuario}):api.post(`/estadia/${reserva.id}/ocupantes`,{...data,operador:usuario});if(tipo==='anular')return api.post(`/consumos-servicios/${anular.id}/anular`,{motivo,operador:usuario});return api.post(`/estadia/${reserva.id}/ocupantes/${data.id}/accion`,{accion:tipo,operador:usuario});},onSuccess:()=>{setEditor(null);setAnular(null);setMotivo('');refrescar();},onError:e=>setError(e.response?.data?.error||'No se pudo guardar el cambio.')});
  const listado=personas.data||[];
  return <section className="rounded-lg border border-borde bg-white p-5 space-y-4">
    <div className="flex flex-wrap gap-2">{(soloPersonas?['Personas']:['Personas',...(puede('verConsumosServicio')?['Cargos por habitación']:[]),...(puedeCuenta?['Cuenta','Condiciones']:[]),'Historial']).map(t=><Button key={t} variante={tab===t?'ok':'secundario'} onClick={()=>setTab(t)}>{t}</Button>)}</div>
    {error&&<p role="alert" className="text-error-texto">{error}</p>}
    {tab==='Personas'&&<>
      <div className="flex justify-between gap-3"><div><h2 className="font-heading text-xl">Personas de la estadía</h2><p className="text-sm text-piedra">El titular no se considera alojado hasta registrarlo e ingresar. Las personas verificadas se ingresan individualmente.</p></div>{puedeEditar&&<Button onClick={()=>{setEditor({});setError('');}}>Agregar persona</Button>}</div>
      {personas.isLoading&&<p>Cargando personas…</p>}{personas.isError&&<p role="alert">No se pudieron cargar los ocupantes.</p>}
      {!listado.length&&!personas.isLoading&&<p className="text-piedra">Todavía no se registraron ocupantes. Agregá también al titular si se aloja.</p>}
      {reserva.habitaciones.map(h=><div key={h.id} className="rounded border border-borde p-3"><h3 className="font-semibold">Habitación {h.numero} · capacidad {h.capacidad}</h3>{listado.filter(p=>(activa(p)||p.asignaciones?.at(-1))?.habitacionId===h.id).map(p=><div key={p.id} className="border-t border-borde py-3 flex flex-wrap justify-between gap-2"><div><strong>{p.nombre} {p.apellido}</strong><p className="text-sm">{p.tipoDocumento} {p.numeroDocumento||'Documento pendiente'} · {p.estado} · {p.verificadoEn?'Verificado':'Datos por verificar'}</p><p className="text-xs text-piedra">Ingreso: {fecha(p.ingresoReal)} · Salida: {fecha(p.salidaReal)}</p></div>{puedeEditar&&<div className="flex flex-wrap gap-2">{['Previsto','Alojado'].includes(p.estado)&&<><Button variante="secundario" onClick={()=>{setError('');setEditor(p);}}>Editar</Button><Button variante="secundario" disabled={mutation.isPending} onClick={()=>mutation.mutate({tipo:'verificar',data:p})}>Verificar datos</Button></>}{p.estado==='Previsto'&&<><Button disabled={!p.verificadoEn||reserva.estado!=='En curso'||mutation.isPending} onClick={()=>mutation.mutate({tipo:'ingresar',data:p})}>Registrar ingreso</Button><Button variante="secundario" disabled={mutation.isPending} onClick={()=>mutation.mutate({tipo:'cancelar',data:p})}>Cancelar ingreso</Button></>}{p.estado==='Alojado'&&<Button variante="secundario" disabled={mutation.isPending} onClick={()=>mutation.mutate({tipo:'retirar',data:p})}>Registrar salida</Button>}</div>}</div>)}</div>)}
    </>}
    {tab==='Cargos por habitación'&&<>{cargos.isError&&<p role="alert">No se pudieron cargar los cargos.</p>}{reserva.habitaciones.map(h=><div key={h.id} className="border border-borde rounded p-4 space-y-3"><div className="flex justify-between"><h3 className="font-semibold">Habitación {h.numero}</h3>{puedeCargos&&<Button onClick={()=>setCargoHabitacion(h.id)}>Agregar cargo</Button>}</div>{(cargos.data||[]).filter(c=>c.habitacionId===h.id).map(c=><div key={c.id} className="flex justify-between gap-3 border-t border-borde py-2"><div><p className={c.anulado?'line-through text-piedra':''}>{c.descripcion||c.tipoServicio} · {c.cantidad||1} × {moneda(c.precioUnitario??c.monto)} · <strong>{moneda(c.monto)}</strong>{c.incluido?' · Incluido en tarifa':''}</p><p className="text-xs text-piedra">{fecha(c.fechaServicio||c.fechaHora)} · Registró: {c.registradoPor}{c.anulado?` · Anulado: ${c.motivoAnulacion}`:''}</p></div>{puedeCargos&&!c.anulado&&<Button variante="secundario" onClick={()=>{setAnular(c);setError('');}}>Anular</Button>}</div>)}<p className="text-right font-semibold">Adicionales: {moneda((cargos.data||[]).filter(c=>c.habitacionId===h.id&&!c.anulado).reduce((s,c)=>s+c.monto,0))}</p></div>)}</>}
    {tab==='Cuenta'&&<>{cuenta.isError&&<p role="alert">No se pudo cargar la cuenta.</p>}{cuenta.data&&<><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Habitación','Alojamiento','Adicionales','Revisión','Total'].map(t=><th key={t} className="text-left p-2">{t}</th>)}</tr></thead><tbody>{cuenta.data.habitaciones.map(h=><tr key={h.habitacionId}>{[h.numero,moneda(h.subtotal),moneda(h.adicionales),moneda(h.verificacion),moneda(h.total)].map((v,i)=><td key={i} className="p-2 border-t border-borde">{v}</td>)}</tr>)}</tbody></table></div><p>Total reserva: <strong>{moneda(cuenta.data.totalAdeudado)}</strong> · Pagado: {moneda(cuenta.data.totalPagado)} · Saldo: <strong>{moneda(cuenta.data.saldo)}</strong></p><p className="text-xs text-piedra">Los pagos pertenecen a la reserva. Los cargos históricos sin habitación identificada se incluyen en el total general.</p><Garantias reservaId={reserva.id} garantias={cuenta.data.garantias||[]} editable={puedeCargos&&puedeCuenta} onExito={refrescar}/></>}</>}
    {tab==='Condiciones'&&<CondicionesHabitaciones reserva={reserva} editable={puedeEditar}/>}
    {tab==='Historial'&&<>{historial.isError&&<p role="alert">No se pudo cargar el historial.</p>}{(historial.data||[]).map(e=><p key={e.id} className="border-b border-borde py-2 text-sm">{fecha(e.fecha)} · {e.accion} · {e.operador}<span className="block text-xs text-piedra">{detalleEvento(e)}</span></p>)}</>}
    {editor&&<Modal titulo={editor.id?'Editar ocupante':'Agregar ocupante'} onClose={()=>setEditor(null)} ancho="max-w-3xl"><PersonaFormulario persona={editor} reserva={reserva} personas={listado} error={error} pendiente={mutation.isPending} onClose={()=>setEditor(null)} onGuardar={data=>mutation.mutate({tipo:'guardar',data})}/></Modal>}
    {cargoHabitacion&&<ConsumoModal reserva={reserva} habitacionIdInicial={cargoHabitacion} onClose={()=>setCargoHabitacion(null)} onExito={()=>{setCargoHabitacion(null);refrescar();}}/>}
    {anular&&<Modal titulo="Anular cargo" onClose={()=>setAnular(null)}><div className="p-5 space-y-3"><p>Se anula el cargo de {moneda(anular.monto)}. El producto consumido no vuelve automáticamente al stock.</p><Input label="Motivo *" value={motivo} onChange={e=>setMotivo(e.target.value)} maxLength={500}/>{error&&<p role="alert">{error}</p>}<Button disabled={!motivo.trim()} cargando={mutation.isPending} onClick={()=>mutation.mutate({tipo:'anular'})}>Confirmar anulación</Button></div></Modal>}
  </section>;
}
export function Garantias({reservaId,garantias,editable,onExito}){
  const {usuario}=useSesion();const [form,setForm]=useState({});const [error,setError]=useState('');const m=useMutation({mutationFn:g=>api.post(`/estadia/${reservaId}/garantia`,{pagoId:g.id,...form[g.id],operador:usuario}),onSuccess:()=>{setError('');setForm({});onExito();},onError:e=>setError(e.response?.data?.error||'No se pudo liquidar la garantía.')});
  return <div className="space-y-3"><h3 className="font-semibold">Garantía de seguridad</h3>{garantias.length===0&&<p className="text-sm text-piedra">Sin garantía registrada.</p>}{garantias.map(g=><div key={g.id} className="rounded border border-borde p-3"><p className="text-sm">Recibida {moneda(g.recibida)} · Aplicada {moneda(g.aplicada)} · Devuelta {moneda(g.devuelta)} · Pendiente {moneda(g.pendiente)}</p>{editable&&g.pendiente>0&&<div className="grid sm:grid-cols-3 gap-2 mt-3">{[['devolver','Devolución realizada'],['aplicar','Aplicar a cuenta'],['motivo','Motivo / referencia']].map(([k,label])=><Input key={k} label={label} type={k==='motivo'?'text':'number'} min="0" step="0.01" value={form[g.id]?.[k]||''} onChange={e=>setForm({...form,[g.id]:{...form[g.id],[k]:e.target.value}})}/>)}<p className="text-xs sm:col-span-3">Registrar una devolución confirma un movimiento realizado fuera del sistema; no transfiere dinero automáticamente.</p><Button cargando={m.isPending} onClick={()=>m.mutate(g)}>Registrar liquidación</Button></div>}</div>)}{error&&<p role="alert" className="text-error-texto">{error}</p>}</div>;
}
